name: synchronize data from api.covid19tracker.ca

on:
  workflow_dispatch:
    branches:
      - optimizations
  schedule:
  - cron: "1 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout optimizations
        uses: actions/checkout@v2

      - name: Get data
        run: ./data.sh

        # Assume we want to merge into same branch
      - name: Commit to branch
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Sync Data"
          git push origin optimizations
